//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qryptio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qryptio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string About_BackButton {
            get {
                return ResourceManager.GetString("About_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open GitHub page.
        /// </summary>
        public static string AboutPage_OpenGithubPage {
            get {
                return ResourceManager.GetString("AboutPage_OpenGithubPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open with Qryptio.
        /// </summary>
        public static string App_ContextMenuOpenWith {
            get {
                return ResourceManager.GetString("App_ContextMenuOpenWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon app_icon {
            get {
                object obj = ResourceManager.GetObject("app_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap app_logo {
            get {
                object obj = ResourceManager.GetObject("app_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qryptio.
        /// </summary>
        public static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string App_Settings {
            get {
                return ResourceManager.GetString("App_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogService_Error {
            get {
                return ResourceManager.GetString("DialogService_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string DialogService_Information {
            get {
                return ResourceManager.GetString("DialogService_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string DialogService_Question {
            get {
                return ResourceManager.GetString("DialogService_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_encrypted {
            get {
                object obj = ResourceManager.GetObject("file_encrypted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_executable {
            get {
                object obj = ResourceManager.GetObject("file_executable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_pictures {
            get {
                object obj = ResourceManager.GetObject("file_pictures", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap file_plain {
            get {
                object obj = ResourceManager.GetObject("file_plain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted.
        /// </summary>
        public static string FileDescription_Encrypted {
            get {
                return ResourceManager.GetString("FileDescription_Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        public static string FileDescription_Executable {
            get {
                return ResourceManager.GetString("FileDescription_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string FileDescription_Picture {
            get {
                return ResourceManager.GetString("FileDescription_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain.
        /// </summary>
        public static string FileDescription_Plain {
            get {
                return ResourceManager.GetString("FileDescription_Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FilePage_BackButton {
            get {
                return ResourceManager.GetString("FilePage_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to cancel operation?.
        /// </summary>
        public static string FilePage_CancellationQuestion {
            get {
                return ResourceManager.GetString("FilePage_CancellationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string FilePage_Decrypt {
            get {
                return ResourceManager.GetString("FilePage_Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string FilePage_Encrypt {
            get {
                return ResourceManager.GetString("FilePage_Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File corrupted.
        /// </summary>
        public static string FilePage_FileCorrupted {
            get {
                return ResourceManager.GetString("FilePage_FileCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid or file corrupted.
        /// </summary>
        public static string FilePage_InvalidPassword {
            get {
                return ResourceManager.GetString("FilePage_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string FilePage_PasswordHint {
            get {
                return ResourceManager.GetString("FilePage_PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string FilePage_UnknownError {
            get {
                return ResourceManager.GetString("FilePage_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainPage_About {
            get {
                return ResourceManager.GetString("MainPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string MainPage_AllFiles {
            get {
                return ResourceManager.GetString("MainPage_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only files allowed.
        /// </summary>
        public static string MainPage_DropHint {
            get {
                return ResourceManager.GetString("MainPage_DropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop file here.
        /// </summary>
        public static string MainPage_DropText {
            get {
                return ResourceManager.GetString("MainPage_DropText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string MainPage_OrText {
            get {
                return ResourceManager.GetString("MainPage_OrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string MainPage_SelectFile {
            get {
                return ResourceManager.GetString("MainPage_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainPage_Settings {
            get {
                return ResourceManager.GetString("MainPage_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete input file.
        /// </summary>
        public static string ResultPage_DeleteInputFile {
            get {
                return ResourceManager.GetString("ResultPage_DeleteInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open directory.
        /// </summary>
        public static string ResultPage_OpenDirectory {
            get {
                return ResourceManager.GetString("ResultPage_OpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed!.
        /// </summary>
        public static string ResultPage_OperationCompleted {
            get {
                return ResourceManager.GetString("ResultPage_OperationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start over.
        /// </summary>
        public static string ResultPage_StartOver {
            get {
                return ResourceManager.GetString("ResultPage_StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the options requires admin rights .
        /// </summary>
        public static string Settings_AdminRightsRequsted {
            get {
                return ResourceManager.GetString("Settings_AdminRightsRequsted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Settings_BackButton {
            get {
                return ResourceManager.GetString("Settings_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove option from context menu.
        /// </summary>
        public static string Settings_DisableContextMenu {
            get {
                return ResourceManager.GetString("Settings_DisableContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add option to context menu.
        /// </summary>
        public static string Settings_EnableContextMenu {
            get {
                return ResourceManager.GetString("Settings_EnableContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature enable/disable error.
        /// </summary>
        public static string Settings_FeatureError {
            get {
                return ResourceManager.GetString("Settings_FeatureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart as Admin.
        /// </summary>
        public static string Settings_RestartButton {
            get {
                return ResourceManager.GetString("Settings_RestartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_info {
            get {
                object obj = ResourceManager.GetObject("ui_info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_settings {
            get {
                object obj = ResourceManager.GetObject("ui_settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
